title: Webkanini Technologies
description: "Consulting and solutions based on free & open source technologies and ERP systems."
baseurl: ""       # keep empty for user/org site
url: "https://webkanini.github.io"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed